= Starter

image:https://img.shields.io/badge/vert.x-3.8.1-purple.svg[link="https://vertx.io"]

This application was generated using http://start.vertx.io

== Building

To launch your tests:
```
./mvnw clean test
```

To package your application:
```
./mvnw clean package
```

To run your application:
```
./mvnw clean compile exec:java
```

== Help

* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]


The challenge is to create a maven project which builds a fat jar that, when run, starts an HTTP server on port 8080. This server should provide a /person endpoint that responds as follows:

POST /person, accepting content-type application/JSON: should parse the JSON body into a Person object. If the body contains an id field return status 400; otherwise allocate a unique numeric id to the person and save the object in an in-memory collection (e.g. a Map or List of some kind). The endpoint should return status 201 and a JSON body containing the Person object including the newly allocated id field.
GET /person This should return all of the stored person objects, including their id fields
GET /person/:id This should return a JSON body of the corresponding person object, if found (with a 200 status) or 404 if the person is not found
If an error occurs during handling of a request, handle this by returning a failure response in JSON.
Use a kotlin data class for Person

Use kotlinx-serialisation to convert from Person to JSON and vice versa

Use a Vertx Router to route the different requests to different handlers

Use a Vertx BodyHandler to simplify dealing with request bodies

Use a Vertx FailureHandler to direct errors to a handler

© 2019 GitHub, Inc.
